############# Dutch navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Over mij"
url = "/about"
weight = 2

[[main]]
name = "Diensten"
url = "/Diensten"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

[[main]]
name = "Blog"
url = "/blog"
weight = 5

[[main]]
name = "Portfolio"
url = "/portfolio"
weight = 6

[[main]]
weight = 4
name = "Pages"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
