############# Dutch navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Over mij"
url = "/about"
weight = 2

[[main]]
name = "Diensten"
url = "/Diensten"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

# [[main]]
# name = "Blog & Portfolio"
# url = "/blog"
# weight = 5

# [[main]]
# name = "Portfolio"
# url = "/portfolio"
# weight = 6


# # footer menu
# [[footer]]
# name = "Over mij"
# url = "/about"
# weight = 1

# [[footer]]
# name = "Prijzen"
# url = "/Diensten"
# weight = 3
